name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Hacer checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v2

      # Paso 2: Configurar la clave SSH para conectar con las EC2
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      # AQUI SE DEBEN COLOCAR LAS DIRECCIONES IP DE LAS 2 INSTANCIAS
          ssh-keyscan -H 3.80.109.76 >> ~/.ssh/known_hosts
          ssh-keyscan -H 54.165.123.67 >> ~/.ssh/known_hosts

      # Paso 3: Desplegar los archivos en la primera instancia EC2
      - name: Deploy to Instance 1
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@3.80.109.76 << 'EOF'
            cd /home/ec2-user/ClaseYML2 || git clone https://github.com/ErickUCE/ClaseYML2.git
            cd ClaseYML2
            git pull origin main  # Actualizar los archivos del repositorio
            sudo cp index.html /var/www/html/  # Copiar index.html al directorio de Nginx
            sudo systemctl restart nginx  # Reiniciar Nginx
          EOF

      # Paso 4: Desplegar los archivos en la segunda instancia EC2
      - name: Deploy to Instance 2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@54.165.123.67 << 'EOF'
            cd /home/ec2-user/ClaseYML2 || git clone https://github.com/ErickUCE/ClaseYML2.git
            cd ClaseYML2
            git pull origin main  # Actualizar los archivos del repositorio
            sudo cp index.html /var/www/html/  # Copiar index.html al directorio de Nginx
            sudo systemctl restart nginx  # Reiniciar Nginx
          EOF

